using Newtonsoft.Json;
using System;
using UnityEngine;

namespace RuneGuardian
{
    public enum GameMode
    {
        CONVEYOR_BELT = 0,
        GRID = 1,
    };

    public enum PinchFinger
    {
		INDEX  = 0,
		MIDDLE = 1,
		RING   = 2,
		PINKY  = 3,
    }


    /// <summary>
    /// Input data for Rune Guardian game.
    /// </summary>
    [Serializable]
    public class InputData
    {
        public GameMode gameMode;
        public bool useRightHand;
        public PinchFinger pinchFingerIndex;

        // should influence the toy spawnner
        public bool enabledDirtyObjects;
        public bool enabledDestroyedObjects;
        public bool enabledUncoloredObjects;
        
        public int dirtyObjectsDrawing;
        public int destroyedObjectsDrawing;
        public int uncoloredObjectsDrawing;

        // should be between 0 and 100
        public int gestureMinScore;
        
        public int numberOfToys;


    }
    /// <summary>
    /// An example of output data.
    /// Only int and bool data types are allowed at this time.
    /// </summary>
    [Serializable]
    public class GameSessionOutputData : GameSessionOutputDataBase
    {
    }


    /// <summary>
    /// Callback for the stop event generated by the exergame.
    /// </summary>

    public class SessionContainer : SessionContainerBase
    {
        [SerializeField]
        protected InputData _inputData;

        [SerializeField] 
        private GameModeManager gameModeManager;

        [SerializeField]
        protected ClinicalUseController _clinicalUseController;
        [SerializeField]
        protected HomeUseController _homeUseController;
        protected GameManagerBase _mainController;

        void Start()
        {
#if (UNITY_EDITOR)
            // Auto-start game in editor for testing
            Invoke("AutoStartGame", 1f);
#endif
        }

#if (UNITY_EDITOR)
        private void AutoStartGame()
        {
            Debug.Log("Auto-starting game in editor mode...");
            OnCustomEvent("startgame");
        }
#endif

        /// <summary>
        /// Event called when the main VR application notifies the exergame to start.
        /// </summary>
        /// <param name="json">The input data of the exergame in JSON format.</param>
        /// 
        public override void OnInit(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);

            Debug.Log($"GAMEMODE {_inputData.gameMode}");

            gameModeManager.PickMode(_inputData.gameMode);

            _clinicalUseController.Init(_inputData);

            _mainController = _clinicalUseController;
        }

        public override void OnInitHomeUse(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);

            gameModeManager.PickMode(_inputData.gameMode);

            _homeUseController.Init(_inputData);

            _mainController = _homeUseController;
        }

        public override void OnUpdate(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);

            _clinicalUseController.UpdateGame(_inputData);
        }

        /// <summary>
        /// Event called when the main VR application notifies the exergame to pause.
        /// </summary>
        public override void OnPause(bool pause)
        {
            //CubeGameManager.instance.Pause(pause);
        }

        /// <summary>
        /// Event called when the main VR application notifies the
        /// exergame to start a custom event.
        /// </summary>
        /// <param name="eventName">The name of the custom event.</param>
        public override void OnCustomEvent(string eventName)
        {
            Debug.Log(eventName);

            if (eventName == "startgame")
            {
                _clinicalUseController.StartGame();
            }

            if (eventName == "stopgame")
            {
                _clinicalUseController.StopGame();
            }
        }

        /// <summary>
        /// Event called when the main VR application notifies the exergame to stop.
        /// </summary>
        public override void OnStop()
        {
            if (_onStop == null)
            {
                return;
            }

            var outputData = _mainController.OutputData;

            string output = JsonConvert.SerializeObject(outputData);

            _onStop(output);
        }
    }
}
