using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace RuneGuardian
{
    public enum RuneDifficulty
    {
        EASY = 0,
        MEDIUM = 1,
        HARD = 2
    }

    /// <summary>
    /// Input data for Rune Guardian game.
    /// Only int and bool data types are allowed at this time.
    /// </summary>
    [Serializable]
    public class InputData
    {
        // Game difficulty and core mechanics
        public RuneDifficulty GameType;
        public bool Haptic;

        // Enemy wave configuration
        public int EnemyCount;
        public int EnemyHealth;
        public int EnemySpeed;
        public int EnemySpawnRate; // milliseconds between spawns

        // Spell configuration based on difficulty
        public int SpellCooldown; // cooldown in seconds
        public int SpellDamage;
        public int MaxSpellsPerRound;

        // Game session parameters
        public int MaxWaves;
        public int RoundDuration; // duration in seconds
        public bool EnableHealthRegen;
        public int HealthRegenRate; // health per second

        // Gesture recognizer parameters
        public int GestureMinPoints; // minimum points for gesture recognition
        public float GestureMinScore; // minimum score threshold for recognition
        public float GestureMinPointDistance; // minimum distance between points

        // Implicit/default parameters
        public int duration; // duration in seconds
        public BodySide BodySide;
    }
    /// <summary>
    /// An example of output data.
    /// Only int and bool data types are allowed at this time.
    /// </summary>
    [Serializable]
    public class GameSessionOutputData : GameSessionOutputDataBase
    {
        public int WavesCompleted;
    }

    /// <summary>
    /// Callback for the stop event generated by the exergame.
    /// </summary>

    public class SessionContainer : SessionContainerBase
    {
        [SerializeField]
        protected InputData _inputData;

        [SerializeField]
        protected ClinicalUseController _clinicalUseController;
        [SerializeField]
        protected HomeUseController _homeUseController;
        protected GameManagerBase _mainController;

        void Start()
        {
#if (UNITY_EDITOR)
            //OnInit("{\"GameType\":\"0\"," +
            //    "\"Haptic\":\"true\"," +
            //    "\"EnemyCount\":\"3\"," +
            //    "\"EnemyHealth\":\"10\"," +
            //    "\"EnemySpeed\":\"2\"," +
            //    "\"EnemySpawnRate\":\"2000\"," +
            //    "\"SpellCooldown\":\"3\"," +
            //    "\"SpellDamage\":\"5\"," +
            //    "\"MaxSpellsPerRound\":\"10\"," +
            //    "\"MaxWaves\":\"5\"," +
            //    "\"RoundDuration\":\"60\"," +
            //    "\"EnableHealthRegen\":\"false\"," +
            //    "\"HealthRegenRate\":\"1\"," +
            //    "\"duration\":\"0\"," +
            //    "\"BodySide\":\"0\"}");
#endif

        }

        /// <summary>
        /// Event called when the main VR application notifies the exergame to start.
        /// </summary>
        /// <param name="json">The input data of the exergame in JSON format.</param>
        /// 
        public override void OnInit(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);

            _clinicalUseController.Init(_inputData);

            _mainController = _clinicalUseController;
        }

        public override void OnInitHomeUse(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);

            _homeUseController.Init(_inputData);

            _mainController = _homeUseController;
        }

        public override void OnUpdate(string json)
        {
            _inputData = JsonUtility.FromJson<InputData>(json);

            _clinicalUseController.UpdateGame(_inputData);
        }

        /// <summary>
        /// Event called when the main VR application notifies the exergame to pause.
        /// </summary>
        public override void OnPause(bool pause)
        {
            //CubeGameManager.instance.Pause(pause);
        }

        /// <summary>
        /// Event called when the main VR application notifies the
        /// exergame to start a custom event.
        /// </summary>
        /// <param name="eventName">The name of the custom event.</param>
        public override void OnCustomEvent(string eventName)
        {
            Debug.Log(eventName);

            if (eventName == "startgame")
            {
                _clinicalUseController.StartGame();
            }

            if (eventName == "stopgame")
            {
                _clinicalUseController.StopGame();
            }
        }

        /// <summary>
        /// Event called when the main VR application notifies the exergame to stop.
        /// </summary>
        public override void OnStop()
        {
            if (_onStop == null)
            {
                return;
            }

            var outputData = _mainController.OutputData;

            string output = JsonConvert.SerializeObject(outputData);

            _onStop(output);
        }
    }
}
